export interface Airdrop {
  id: string;
  name: string;
  symbol: string;
  category: "DeFi" | "Layer 2" | "NFT" | "Gaming" | "Meme" | "AI" | "Quest Platform" | "Infrastructure";
  description: string;
  reward: string;
  rewardType: "Token" | "USD" | "NFT" | "Points" | "Whitelist";
  difficulty: "Easy" | "Medium" | "Hard";
  status: "Active" | "Upcoming" | "Ended";
  deadline: string; // YYYY-MM-DD or "TBA"
  verified: boolean;
  trending: boolean;
  tasks: string[];
  url: string;
  icon: string;
  gradient: string;
}

export const airdropsData: Airdrop[] = [
  // ═══════ QUEST PLATFORMS ═══════
  {
    id: "layer3",
    name: "Layer3",
    symbol: "L3",
    category: "Quest Platform",
    description: "Complete on-chain quests across multiple ecosystems and earn XP + potential token rewards.",
    reward: "XP + Future Token",
    rewardType: "Points",
    difficulty: "Easy",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Sign up with wallet", "Complete daily quests", "Collect XP", "Refer friends"],
    url: "https://layer3.xyz",
    icon: "🎯",
    gradient: "from-purple-500 to-pink-500",
  },
  {
    id: "galxe",
    name: "Galxe",
    symbol: "GAL",
    category: "Quest Platform",
    description: "Web3 credential platform. Complete campaigns to earn NFTs and token rewards.",
    reward: "NFTs + Tokens",
    rewardType: "NFT",
    difficulty: "Easy",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Connect wallet", "Complete campaigns", "Collect credentials", "Claim rewards"],
    url: "https://galxe.com",
    icon: "🌌",
    gradient: "from-blue-500 to-cyan-500",
  },
  {
    id: "zealy",
    name: "Zealy",
    symbol: "ZLY",
    category: "Quest Platform",
    description: "Community engagement platform. Earn XP by completing tasks for various projects.",
    reward: "XP + Whitelist",
    rewardType: "Whitelist",
    difficulty: "Easy",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: false,
    tasks: ["Join communities", "Complete quests", "Level up XP", "Get whitelisted"],
    url: "https://zealy.io",
    icon: "⚡",
    gradient: "from-yellow-500 to-orange-500",
  },
  {
    id: "intract",
    name: "Intract",
    symbol: "INT",
    category: "Quest Platform",
    description: "Web3 discovery and engagement platform with on-chain task rewards.",
    reward: "Token + XP",
    rewardType: "Token",
    difficulty: "Easy",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Complete quests", "Interact with dApps", "Earn XP points", "Redeem rewards"],
    url: "https://www.intract.io",
    icon: "🔮",
    gradient: "from-indigo-500 to-purple-500",
  },
  {
    id: "questn",
    name: "QuestN",
    symbol: "QN",
    category: "Quest Platform",
    description: "Task platform for NFT and token campaigns from new crypto projects.",
    reward: "NFT + Tokens",
    rewardType: "NFT",
    difficulty: "Easy",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: false,
    tasks: ["Sign up", "Complete quests", "Earn NFTs", "Get token airdrops"],
    url: "https://questn.com",
    icon: "🎮",
    gradient: "from-green-500 to-teal-500",
  },

  // ═══════ LAYER 2 & INFRASTRUCTURE ═══════
  {
    id: "linea",
    name: "Linea",
    symbol: "LINEA",
    category: "Layer 2",
    description: "ConsenSys zkEVM Layer 2. Bridge and use dApps to potentially qualify for airdrop.",
    reward: "$100-$1000",
    rewardType: "USD",
    difficulty: "Medium",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Bridge to Linea", "Use dApps", "Provide liquidity", "Mint NFTs"],
    url: "https://linea.build",
    icon: "🌐",
    gradient: "from-blue-600 to-indigo-600",
  },
  {
    id: "scroll",
    name: "Scroll",
    symbol: "SCR",
    category: "Layer 2",
    description: "zkEVM Layer 2 solution. Use ecosystem to potentially qualify for future airdrop.",
    reward: "$200-$2000",
    rewardType: "USD",
    difficulty: "Medium",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Bridge ETH to Scroll", "Swap tokens", "Provide liquidity", "Interact with dApps"],
    url: "https://scroll.io",
    icon: "📜",
    gradient: "from-orange-500 to-red-500",
  },
  {
    id: "zksync",
    name: "zkSync Era",
    symbol: "ZK",
    category: "Layer 2",
    description: "Advanced zkRollup with growing ecosystem. Ongoing airdrop opportunities.",
    reward: "$500-$5000",
    rewardType: "USD",
    difficulty: "Medium",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Bridge assets", "Trade on DEXs", "Mint NFTs", "Use lending protocols"],
    url: "https://zksync.io",
    icon: "⚡",
    gradient: "from-purple-600 to-blue-600",
  },
  {
    id: "starknet",
    name: "Starknet",
    symbol: "STRK",
    category: "Layer 2",
    description: "STARK-based Layer 2 scaling solution. Active ecosystem with airdrop potential.",
    reward: "$300-$3000",
    rewardType: "USD",
    difficulty: "Hard",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Bridge to Starknet", "Use Argent wallet", "Trade on JediSwap", "Provide liquidity"],
    url: "https://starknet.io",
    icon: "⭐",
    gradient: "from-pink-500 to-purple-500",
  },
  {
    id: "base",
    name: "Base",
    symbol: "BASE",
    category: "Layer 2",
    description: "Coinbase's Layer 2. Growing ecosystem with potential future rewards.",
    reward: "TBA",
    rewardType: "Token",
    difficulty: "Easy",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Bridge to Base", "Use dApps", "Mint NFTs", "Trade tokens"],
    url: "https://base.org",
    icon: "🔵",
    gradient: "from-blue-500 to-blue-700",
  },

  // ═══════ DeFi ═══════
  {
    id: "hyperliquid",
    name: "Hyperliquid",
    symbol: "HYPE",
    category: "DeFi",
    description: "Decentralized perpetuals exchange. Trade to earn HYPE points for airdrop.",
    reward: "HYPE Tokens",
    rewardType: "Token",
    difficulty: "Medium",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Deposit funds", "Trade perpetuals", "Provide liquidity", "Refer users"],
    url: "https://hyperliquid.xyz",
    icon: "💧",
    gradient: "from-cyan-500 to-blue-500",
  },
  {
    id: "eigenlayer",
    name: "EigenLayer",
    symbol: "EIGEN",
    category: "DeFi",
    description: "Restaking protocol on Ethereum. Restake to earn EIGEN points.",
    reward: "EIGEN Tokens",
    rewardType: "Token",
    difficulty: "Medium",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Restake ETH/LSTs", "Delegate to operators", "Earn points", "Refer friends"],
    url: "https://www.eigenlayer.xyz",
    icon: "🔷",
    gradient: "from-blue-500 to-indigo-600",
  },
  {
    id: "pendle",
    name: "Pendle",
    symbol: "PENDLE",
    category: "DeFi",
    description: "Yield tokenization protocol. Trade yield-bearing assets for rewards.",
    reward: "Points + Tokens",
    rewardType: "Points",
    difficulty: "Hard",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Deposit yield tokens", "Trade PT/YT", "Provide liquidity", "Vote in governance"],
    url: "https://www.pendle.finance",
    icon: "📊",
    gradient: "from-green-500 to-emerald-500",
  },
  {
    id: "kamino",
    name: "Kamino Finance",
    symbol: "KMNO",
    category: "DeFi",
    description: "Solana lending & liquidity protocol. Use to earn KMNO points.",
    reward: "KMNO Tokens",
    rewardType: "Token",
    difficulty: "Easy",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: false,
    tasks: ["Deposit on Solana", "Borrow assets", "Provide liquidity", "Complete missions"],
    url: "https://kamino.finance",
    icon: "🐦",
    gradient: "from-purple-500 to-pink-500",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    symbol: "JUP",
    category: "DeFi",
    description: "Leading Solana DEX aggregator. Trade to potentially earn future rewards.",
    reward: "JUP Tokens",
    rewardType: "Token",
    difficulty: "Easy",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Trade on Jupiter", "Use limit orders", "Refer traders", "Stake JUP"],
    url: "https://jup.ag",
    icon: "🪐",
    gradient: "from-orange-500 to-yellow-500",
  },

  // ═══════ AI & INFRASTRUCTURE ═══════
  {
    id: "grass",
    name: "Grass",
    symbol: "GRASS",
    category: "AI",
    description: "Decentralized bandwidth network. Share internet to earn GRASS tokens.",
    reward: "GRASS Tokens",
    rewardType: "Token",
    difficulty: "Easy",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Install extension", "Keep it running", "Earn passive rewards", "Refer users"],
    url: "https://www.getgrass.io",
    icon: "🌱",
    gradient: "from-green-500 to-lime-500",
  },
  {
    id: "gensyn",
    name: "Gensyn",
    symbol: "GEN",
    category: "AI",
    description: "Decentralized AI training network. Early adopters get airdrop potential.",
    reward: "GEN Tokens",
    rewardType: "Token",
    difficulty: "Hard",
    status: "Upcoming",
    deadline: "TBA",
    verified: true,
    trending: false,
    tasks: ["Join waitlist", "Contribute compute", "Participate in testnet", "Follow updates"],
    url: "https://gensyn.ai",
    icon: "🤖",
    gradient: "from-cyan-500 to-blue-500",
  },
  {
    id: "io-net",
    name: "IO.NET",
    symbol: "IO",
    category: "AI",
    description: "Decentralized GPU cloud for AI. Contribute compute or use for airdrop.",
    reward: "IO Tokens",
    rewardType: "Token",
    difficulty: "Medium",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Sign up", "Contribute GPU", "Use compute", "Refer users"],
    url: "https://io.net",
    icon: "🖥️",
    gradient: "from-red-500 to-pink-500",
  },

  // ═══════ GAMING ═══════
  {
    id: "immutable-x",
    name: "Immutable X",
    symbol: "IMX",
    category: "Gaming",
    description: "Leading Web3 gaming platform. Play games to earn IMX rewards.",
    reward: "IMX + NFTs",
    rewardType: "Token",
    difficulty: "Easy",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: false,
    tasks: ["Create account", "Play games", "Complete quests", "Trade NFTs"],
    url: "https://www.immutable.com",
    icon: "🎮",
    gradient: "from-indigo-500 to-purple-500",
  },
  {
    id: "pixels",
    name: "Pixels",
    symbol: "PIXEL",
    category: "Gaming",
    description: "Casual Web3 farming game. Play to earn PIXEL tokens daily.",
    reward: "PIXEL Tokens",
    rewardType: "Token",
    difficulty: "Easy",
    status: "Active",
    deadline: "TBA",
    verified: true,
    trending: true,
    tasks: ["Sign up", "Play daily", "Complete quests", "Farm crops"],
    url: "https://pixels.xyz",
    icon: "🌾",
    gradient: "from-yellow-500 to-green-500",
  },

  // ═══════ MEME & OTHERS ═══════
  {
    id: "pepe-unchained",
    name: "Pepe Unchained",
    symbol: "PEPU",
    category: "Meme",
    description: "Pepe-themed Layer 2 blockchain. Presale + airdrop for early participants.",
    reward: "PEPU Tokens",
    rewardType: "Token",
    difficulty: "Easy",
    status: "Upcoming",
    deadline: "TBA",
    verified: false,
    trending: true,
    tasks: ["Join presale", "Stake PEPU", "Refer friends", "Follow socials"],
    url: "https://pepeunchained.com",
    icon: "🐸",
    gradient: "from-green-500 to-yellow-500",
  },
  {
    id: "coinmarketcap",
    name: "CoinMarketCap",
    symbol: "CMC",
    category: "Quest Platform",
    description: "Track and participate in listed airdrops from verified crypto projects.",
    reward: "Various",
    rewardType: "Token",
    difficulty: "Easy",
    status: "Active",
    deadline: "Ongoing",
    verified: true,
    trending: false,
    tasks: ["Sign up", "Complete tasks", "Verify wallet", "Claim rewards"],
    url: "https://coinmarketcap.com/airdrop/",
    icon: "📊",
    gradient: "from-blue-500 to-teal-500",
  },
];

export const categories = ["All", "DeFi", "Layer 2", "NFT", "Gaming", "Meme", "AI", "Quest Platform", "Infrastructure"];
export const difficulties = ["All", "Easy", "Medium", "Hard"];
export const statuses = ["All", "Active", "Upcoming", "Ended"];